on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
      - run: |
          pip install requests neo4j pinecone-client google-generativeai
      - env:
          gemini_api_key: ${{ secrets.gemini_api_key }}
          neo4j_uri: ${{ secrets.neo4j_uri }}
          neo4j_user: ${{ secrets.neo4j_user }}
          neo4j_password: ${{ secrets.neo4j_password }}
          pinecone_api_key: ${{ secrets.pinecone_api_key }}
        run: python scraper.py
